GRANT CONNECT ON DATABASE chat TO me;
GRANT USAGE, CREATE ON SCHEMA public TO me;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO me;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO me;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO me;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO me;
